//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinSpy.rc
//
#define IDD_TAB_GENERAL                 101
#define IDB_DRAGTOOL1                   103
#define IDC_CURSOR1                     104
#define IDI_ICON1                       105
#define IDD_TAB_STYLES                  106
#define IDD_TAB_PROPERTIES              107
#define IDD_TAB_CLASS                   108
#define IDD_TAB_WINDOWS                 109
#define IDD_TAB_SCROLLBARS              110
#define IDD_MAIN                        111
#define IDB_BITMAP2                     113
#define IDB_WINDOW_INVISIBLE            113
#define IDB_DRAGTOOL2                   116
#define IDB_BITMAP3                     117
#define IDB_WINDOW_VISIBLE              117
#define IDD_STYLE_EDIT                  118
#define IDI_ICON5                       119
#define IDD_OPTIONS                     121
#define IDI_ICON10                      125
#define IDB_CHECK1                      126
#define IDB_CHECK2                      127
#define IDI_ICON17                      135
#define IDD_ADJUSTWINPOS                136
#define IDR_MENU2                       137
#define IDI_ICON16                      142
#define IDI_ICON18                      143
#define IDR_ACCELERATOR1                144
#define IDD_TAB_PROCESS                 145
#define IDR_MENU1                       146
#define IDR_MENU3                       149
#define IDB_BITMAP4                     152
#define IDB_PIN_BITMAP                  153
#define IDR_RT_MANIFEST1                159
#define IDC_LIST1                       1000
#define IDC_DRAGGER                     1001
#define IDC_LIST2                       1001
#define IDC_HANDLE                      1002
#define IDC_CAPTION2                    1003
#define IDC_WINDOWBYTES                 1004
#define IDC_MINIMIZE                    1005
#define IDC_CLASS                       1006
#define IDC_HIDDEN                      1006
#define IDC_STYLE                       1007
#define IDC_RECTANGLE                   1008
#define IDC_CLIENTRECT                  1010
#define IDC_WINDOWPROC2                 1011
#define IDC_INSTANCE                    1012
#define IDC_CONTROLID                   1013
#define IDC_USERDATA                    1014
#define IDC_EDIT1                       1015
#define IDC_CLASSNAME                   1015
#define IDC_EDITY                       1016
#define IDC_STYLELIST                   1017
#define IDC_EDITW                       1017
#define IDC_PID                         1017
#define IDC_BYTESLIST                   1018
#define IDC_EDITH                       1018
#define IDC_TID                         1018
#define IDC_TAB1                        1019
#define IDC_CLASSBYTES                  1020
#define IDC_ATOM                        1021
#define IDC_MENUHANDLE                  1022
#define IDC_ICONHANDLE                  1023
#define IDC_CURSORHANDLE                1024
#define IDC_BKGNDBRUSH                  1025
#define IDC_INSTANCEHANDLE              1026
#define IDC_WNDPROC                     1027
#define IDC_CLASSPROC                   1028
#define IDC_PARENT                      1029
#define IDC_OWNER                       1030
#define IDC_HSTATE                      1032
#define IDC_HMIN                        1033
#define IDC_HMAX                        1034
#define IDC_HPOS                        1035
#define IDC_HPAGE                       1036
#define IDC_CAPTURE                     1037
#define IDC_TREE1                       1038
#define IDC_STYLEEX                     1040
#define IDC_TAB2                        1042
#define IDC_LOCATE                      1044
#define IDC_REFRESH                     1045
#define IDC_DELETE                      1045
#define IDC_RESET                       1045
#define IDC_PROCESS_MENU                1045
#define IDC_FLASH                       1046
#define IDC_VSTATE                      1047
#define IDC_EDITSTYLE                   1047
#define IDC_VMIN                        1048
#define IDC_EDITSTYLEEX                 1048
#define IDC_VMAX                        1049
#define IDC_VPOS                        1050
#define IDC_VPAGE                       1051
#define IDC_CHECK1                      1051
#define IDC_OPTIONS_SAVEPOS             1051
#define IDC_CHECK2                      1052
#define IDC_OPTIONS_AUTOEXPAND          1052
#define IDC_CHECK4                      1054
#define IDC_OPTIONS_SHOWINCAPTION       1054
#define IDC_CHECK6                      1056
#define IDC_CHECK7                      1057
#define IDC_OPTIONS_SHOWHIDDEN          1057
#define IDC_CHECK8                      1058
#define IDC_CHECK3                      1059
#define IDC_OPTIONS_INCHANDLE           1059
#define IDC_CHECK9                      1060
#define IDC_OPTIONS_INCCLASS            1060
#define IDC_EDITSIZE                    1061
#define IDC_CHECK10                     1061
#define IDC_OPTIONS_FULLDRAG            1061
#define IDC_SETCAPTION                  1062
#define IDC_ADJUST                      1062
#define IDC_OPTIONS_DIR                 1062
#define IDC_EDITX                       1063
#define IDC_OPTIONS_TOOLTIPS            1063
#define IDC_SPINX                       1064
#define IDC_SPINY                       1065
#define IDC_APPLY                       1065
#define IDC_SPINW                       1066
#define IDC_CAPTION1                    1066
#define IDC_SPINH                       1067
#define IDC_PROCESSNAME                 1067
#define IDC_PROCESSNAME2                1068
#define IDC_PROCESSPATH                 1068
#define IDC_HANDLE_MENU                 1069
#define IDC_EXPAND                      1070
#define IDC_WINDOWPROC                  1070
#define IDC_CLEAR                       1071
#define IDM_GENERAL_ONTOP               40003
#define IDM_GENERAL_VISIBLE             40004
#define IDM_GENERAL_ENABLED             40005
#define IDM_GENERAL_DELETE              40006
#define IDM_WINSPY_REFRESH              40007
#define IDM_WINSPY_MINIMIZE             40008
#define IDM_WINSPY_NORMAL               40009
#define IDM_WINSPY_EXPANDED             40010
#define IDM_WINSPY_GENERAL              40011
#define IDM_WINSPY_STYLES               40012
#define IDM_WINSPY_PROPERTIES           40013
#define IDM_WINSPY_CLASS                40014
#define IDM_WINSPY_WINDOWS              40015
#define IDM_WINSPY_SCROLLBARS           40016
#define IDM_WINSPY_TERMINATE            40018
#define IDM_WINSPY_POSTQUIT             40019
#define IDM_WINSPY_MOVE                 40020
#define IDM_POPUP_SETPOS                40020
#define IDM_WINSPY_KILLPROC             40021
#define IDM_POPUP_VISIBLE               40023
#define IDM_POPUP_ENABLED               40024
#define IDM_POPUP_ONTOP                 40025
#define IDM_POPUP_CLOSE                 40026
#define IDM_POPUP_TOFRONT               40027
#define IDM_POPUP_TOBACK                40028
#define IDM_WINSPY_PIN                  40029
#define IDM_WINSPY_HELP                 40031
#define IDM_WINSPY_TOGGLE               40032
#define IDM_WINSPY_TOGGLEEXP            40033
#define IDM_WINSPY_OPTIONS              40034
#define IDM_WINSPY_ONTOP                40035
#define IDM_WINSPY_ZOOMTR               40036
#define IDM_WINSPY_ZOOMTL               40037
#define IDM_WINSPY_ZOOMBR               40038
#define IDM_WINSPY_ZOOMBL               40039
#define IDM_WINSPY_FINDEXE              40040
#define IDM_POPUP_CAPTURE               40041
#define IDM_POPUP_COPY                  40041
#define IDM_POPUP_SAVE                  40042
#define IDM_POPUP_DESTROY               40043

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         40044
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
